# Определите класс пользовательского исключения NegativeNumberError. Напишите функцию check_positive(number),
# которая вызывает это исключение, если переданное число отрицательное.